// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIktGN8aXWhdbuDz-1iWddR-h3opD-t6Y',
    appId: '1:41577480555:web:8bbdf18c1d77fb7cb64c2e',
    messagingSenderId: '41577480555',
    projectId: 'notes-app-6da4e',
    authDomain: 'notes-app-6da4e.firebaseapp.com',
    storageBucket: 'notes-app-6da4e.appspot.com',
    measurementId: 'G-J9F7GZXK1R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEhiqU3Wtag0Q-02RLDAneUHfBs48ATI4',
    appId: '1:41577480555:android:223ff584e87665bfb64c2e',
    messagingSenderId: '41577480555',
    projectId: 'notes-app-6da4e',
    storageBucket: 'notes-app-6da4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSyVYMXBEcXBqQQf7Mgjoy5frA6BaAUy8',
    appId: '1:41577480555:ios:2e6aa67cf88accc8b64c2e',
    messagingSenderId: '41577480555',
    projectId: 'notes-app-6da4e',
    storageBucket: 'notes-app-6da4e.appspot.com',
    androidClientId: '41577480555-rh37ppbbmgitmlouvnp9nji7b97its4r.apps.googleusercontent.com',
    iosClientId: '41577480555-4aqkt8h8e8hobsefn8m9mitjs05u4cb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.qboxAdmin',
  );
}
